branches:
  only:
    - master

services:
  - docker

jobs:
  include:
    - stage: SpringBoot gradle build & Build Gradle Docker Image
      language: java
      jdk:
        - openjdk11

      #cache:
      #  directories:
      #    - '$HOME/ .m2/repository'
      #    - '$HOME/ .gradle'
      before_install:
        - chmod +x gradlew
      script:
        - ./gradlew clean build
        - docker build -t $SPRING_REPO -f ./Dockerfile .
        - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        - docker push $SPRING_REPO

    - stage: Build Nginx Docker image
      sudo: required
      language: generic
      script:
        - docker build -t $NGINX_REPO -f ./Dockerfile-nginx .
        - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        - docker push $NGINX_REPO

    - stage: Deploy Stage
      language: generic

      before_deploy:
        - mkdir ready-deploy
        - cp ./docker-compose.yaml ready-deploy
        - cp ./appspec.yml ready-deploy
        - cp ./scripts/docker-hub.sh ready-deploy
        - cd ready-deploy && zip -r prac-built *
        - cd ../ && mkdir -p deploy
        - mv ready-deploy/prac-built.zip deploy/prac-built.zip

      deploy:
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_ACCESS_SECRET
          bucket: practice-build
          region: ap-northeast-2
          skip_cleanup: true
          acl: private
          local_dir: deploy
          wait-until-deployed: true

        - provider: codedeploy
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_ACCESS_SECRET
          bucket: practice-build
          key: prac-built.zip
          bundle_type: zip
          application: practiceservice
          deployment_group: practiceservice-group
          region: ap-northeast-2
          wait-until-deployed: true

      after_success:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL


