version: "3"
services:
  web:
    image: adultkim/jpa-nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  spring:
    build: .
    image: adultkim/jpapractice:latest
    container_name: server
    expose:
      - 8081
    ports:
      - "8081:8081"
    environment:
      active: prod

